### ISSUE TITLE
Qamets qatan for יָמִים?

### ISSUE THREAD

**Issue by m-yac** [charlesLoder/havarotjs#103]
I was surprised to see "יָמִים" in the list of words which get a qamets qatan, I personally have only ever encountered that word pronounced as "yamim" (with a qamets) and not as "yomim" (with a qamets qatan).

I searched through the text of the [Miqra according to the Masorah](https://en.wikisource.org/wiki/User:Dovi/Miqra_according_to_the_Masorah) (the Hebrew source for [Sefaria's Tanakh](https://www.sefaria.org/texts/Tanakh)) – which adds Unicode qamets qatan markings – and I didn't find any instances of "יָמִים" having a qamets qatan:
https://www.sefaria.org/search?q=יׇמ%D6%B4ים&tab=text&tpathFilters=Tanakh&tvar=1&tsort=relevance&svar=1&ssort=relevance

Of course, I might have missed something, or there might be a different tradition that pronounces this word as "yomim" that MAM doesn't follow. What prompted the addition of this word to the list?

**Comment by charlesLoder** [comment]
Someone else asked the same question [here](http://bhebrew.biblicalhumanities.org/viewtopic.php?p=30635#p30635), but see the discussion about the [DSS material](http://bhebrew.biblicalhumanities.org/viewtopic.php?p=30654#p30654) a little further along.

In short, I've always learned that because it was from an etymological /o/ and the DSS evidence of יומים indicates that it is a qamets qatan.

Of course:
- I can very easily be wrong (as can be seen from the different opinions in the thread)
- just because it _should_ be, doesn't mean anyone realizes it as such

I'll do a little more digging.

I even wonder if having the qametsQatan.ts list as an option would be better (with the current state as the default option)

**Comment by charlesLoder** [comment]
@m-yac 

Ok, [this thread](https://twitter.com/charles_loder/status/1630200628604555266) convinced me.

I'm removing it from the list.
